name: Publish to Cloudflare Pages
on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: shun-shobon/actions/setup-node@master
        with:
          node-version: "lts/*"

      - run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kibou-dev
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
